PAWMartes/PAWMartes/PAWMartes/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PAWMarte.Models;
using PAWMartes.Models;

namespace PAWMartes.Controllers
{
    public class CategoriaController : Controller
    {
        private readonly PAWContext _context;

        public CategoriaController(PAWContext context)
        {
            _context = context;
        }

        // GET: Categoria
        public async Task<IActionResult> Index()
        {
            var pAWContext = _context.Categoria.Include(c => c.Usuario);
            return View(await pAWContext.ToListAsync());
        }

        // GET: Categoria/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoria = await _context.Categoria
                .Include(c => c.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (categoria == null)
            {
                return NotFound();
            }

            return View(categoria);
        }

        // GET: Categoria/Create
        public IActionResult Create()
        {
           // Se tiene que obtener el usuario actual AQUI para ponerlo automaticamente
            //ViewData["UsuarioId"] = new SelectList(_context.Usuario, "Id", "Contraseña");
            return View();
        }

        // POST: Categoria/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Descripcion,Estado")] Categoria categoria)
        {
            // Se tiene que obtener el usuario desde la sesion
            var username = HttpContext.Session.GetString("usuario");
            var usuario = _context.Usuario.FirstOrDefault(u => u.Username == username);
            if (usuario == null)
            {
                return RedirectToAction("Index", "Evento");
            }
            // Se asigna el usuario actual en la sesion
            categoria.UsuarioId = usuario.Id;

            categoria.FechaRegistro = DateTime.Now;
            if (ModelState.IsValid)
            {
                _context.Add(categoria);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            //ViewData["UsuarioId"] = new SelectList(_context.Usuario, "Id", "Contraseña", categoria.UsuarioId);
            return View(categoria);
        }

        // GET: Categoria/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var categoria = await _context.Categoria.FindAsync(id);
            if (categoria == null)
            {
                return NotFound();
            }
            //ViewData["UsuarioId"] = new SelectList(_context.Usuario, "Id", "Contraseña", categoria.UsuarioId);
            return View(categoria);
        }

        // POST: Categoria/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Descripcion,Estado,FechaRegistro,UsuarioId")] Categoria categoria)
        {
            if (id != categoria.Id)
            {
                return NotFound();
            }
            // Se tiene que obtener el usuario desde la sesion
            var username = HttpContext.Session.GetString("usuario");
            var usuario = _context.Usuario.FirstOrDefault(u => u.Username == username);
            if (usuario == null)
            {
                return RedirectToAction("Index", "Evento");
            }
            // Se asigna el usuario actual en la sesion
            categoria.UsuarioId = usuario.Id;

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(categoria);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoriaExists(categoria.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            //ViewData["UsuarioId"] = new SelectList(_context.Usuario, "Id", "Contraseña", categoria.UsuarioId);
            return View(categoria);
        }

        // GET: Categoria/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoria = await _context.Categoria
                .Include(c => c.Usuario)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (categoria == null)
            {
                return NotFound();
            }

            return View(categoria);
        }

        // POST: Categoria/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var categoria = await _context.Categoria.FindAsync(id);
            if (categoria != null)
            {
                _context.Categoria.Remove(categoria);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoriaExists(int id)
        {
            return _context.Categoria.Any(e => e.Id == id);
        }
    }
}

PAWMartes/PAWMartes/PAWMartes/Views/Shared/LayoutPlant02.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PAWMartes</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/Plant02/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Plant02/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/Plant02/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/Plant02/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/Plant02/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Main CSS File -->
    <link href="~/Plant02/css/main.css" rel="stylesheet">
</head>
<body>
    <header id="header" class="header dark-background d-flex flex-column">
        <i class="header-toggle d-xl-none bi bi-list"></i>
        <div class="profile-img">
            <img src="~/plant02/img/my-profile-img.jpg" alt="" class="img-fluid rounded-circle">
        </div>

        <a href="index.html" class="logo d-flex align-items-center justify-content-center">
            <h1 class="sitename">PAW</h1>
        </a>

        <nav id="navmenu" class="navmenu">
            <ul>
                <li>
                    <a class="active" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-house navicon"></i> Home</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Home" asp-action="Privacy"><i class="bi bi-file-earmark-text navicon"></i> Privacy</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Usuario" asp-action="Index"><i class="bi bi-person navicon"></i> Usuarios</a>
                </li>
            </ul>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer id="footer" class="footer position-relative light-background">

        <div class="container">
            <div class="copyright text-center ">
                <p>© <span>Copyright</span> <strong class="px-1 sitename">PAW</strong> <span>All Rights Reserved</span>  - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></p>
            </div>
            <div class="credits">
                Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a> Distributed by <a href="https://themewagon.com">ThemeWagon</a>
            </div>
        </div>

    </footer>
    <!-- Vendor JS Files -->
    <script src="~/Plant02/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/Plant02/vendor/php-email-form/validate.js"></script>
    <script src="~/Plant02/vendor/aos/aos.js"></script>
    <script src="~/Plant02/vendor/typed.js/typed.umd.js"></script>
    <script src="~/Plant02/vendor/purecounter/purecounter_vanilla.js"></script>
    <script src="~/Plant02/vendor/waypoints/noframework.waypoints.js"></script>
    <script src="~/Plant02/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/Plant02/vendor/imagesloaded/imagesloaded.pkgd.min.js"></script>
    <script src="~/Plant02/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/Plant02/vendor/swiper/swiper-bundle.min.js"></script>

    <!-- Main JS File -->
    <script src="~/Plant02/js/main.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PAWMartes/PAWMartes/PAWMartes/Views/Shared/_Encabezado.cshtml
<header id="header" class="header d-flex align-items-center sticky-top">
    <div class="container-fluid container-xl position-relative d-flex align-items-center">
        <a asp-action="Index" asp-controller="Home" class="logo d-flex align-items-center me-auto">
            <h1 class="sitename">EventCorp</h1>
        </a>

        <nav id="navmenu" class="navmenu">
            <ul>

            </ul>
            <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
        </nav>


    </div>
</header>

PAWMartes/PAWMartes/PAWMartes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PAWMartes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PAWMartes.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PAWMartes</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Index">Usuarios</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - PAWMartes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PAWMartes/PAWMartes/PAWMartes/Views/Shared/_LayoutPlant01.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PAWMartes</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/Plant01/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Plant01/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/Plant01/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/Plant01/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/Plant01/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Main CSS File -->
    <link href="~/Plant01/css/main.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>
<body>

    @Html.Partial("_Encabezado");

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @Html.Partial("_PiePagina");
    <!-- Scroll Top -->
    <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Preloader -->
    <div id="preloader"></div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- Vendor JS Files -->
    <script src="~/Plant01/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/Plant01/vendor/php-email-form/validate.js"></script>
    <script src="~/Plant01/vendor/aos/aos.js"></script>
    <script src="~/Plant01/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/Plant01/vendor/purecounter/purecounter_vanilla.js"></script>
    <script src="~/Plant01/vendor/imagesloaded/imagesloaded.pkgd.min.js"></script>
    <script src="~/Plant01/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/Plant01/vendor/swiper/swiper-bundle.min.js"></script>

    <!-- Main JS File -->
    <script src="~/Plant01/js/main.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PAWMartes/PAWMartes/PAWMartes/Views/Shared/_LayoutPlant02.cshtml
@using Microsoft.AspNetCore.Http
@{
    // Alternativa usando ViewContext
    var rol = ViewContext.HttpContext.Session.GetString("Rol");
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PAWMartes</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Raleway:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/Plant02/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Plant02/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/Plant02/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/Plant02/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/Plant02/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Main CSS File -->
    <link href="~/Plant02/css/main.css" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>
<body>
    <header id="header" class="header  d-flex flex-column">
        <i class="header-toggle d-xl-none bi bi-list"></i>
        <div class="profile-img">
            <img src="~/plant02/img/my-profile-img.jpg" alt="" class="img-fluid rounded-circle">
        </div>

        <a href="index.html" class="logo d-flex align-items-center justify-content-center">
            <h1 class="sitename">EventCorp</h1>
        </a>

        <nav id="navmenu" class="navmenu">
            <ul>
                <li>
                    <a class="active" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-house navicon"></i> Home</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Home" asp-action="Privacy"><i class="bi bi-file-earmark-text navicon"></i> Privacy</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Home" asp-action="ListaServicios"><i class="bi bi-file-earmark-text navicon"></i> Servicios</a>
                </li>
                @if (rol == "Admin")
                    {
                        <li>
                            <a asp-area="" asp-controller="Usuario" asp-action="Lista"><i class="bi bi-person navicon"></i> Usuarios</a>
                        </li>
                    }        
           
                <li>
                    <a asp-area="" asp-controller="Evento" asp-action="Index"><i class="bi bi-person navicon"></i> Eventos</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Categoria" asp-action="Index"><i class="bi bi-person navicon"></i> Categorias</a>
                </li>
 
                <li>
                    <a asp-area="" asp-controller="Usuario" asp-action="CerrarSesion"><i class="bi bi-person navicon"></i> Logout</a>
                </li>
                



            </ul>
        </nav>
    </header>



    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer id="footer" class="footer position-relative light-background">

        <div class="container">
            <div class="copyright text-center ">
                <p>© <span>Copyright</span> <strong class="px-1 sitename">EventCorp</strong> <span>All Rights Reserved</span>  - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></p>
            </div>
            <div class="credits">
                Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a> Distributed by <a href="https://themewagon.com">ThemeWagon</a>
            </div>
        </div>

    </footer>

    <!-- Scroll Top -->
    <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>


    <!-- Vendor JS Files -->
    <script src="~/Plant02/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/Plant02/vendor/php-email-form/validate.js"></script>
    <script src="~/Plant02/vendor/aos/aos.js"></script>
    <script src="~/Plant02/vendor/typed.js/typed.umd.js"></script>
    <script src="~/Plant02/vendor/purecounter/purecounter_vanilla.js"></script>
    <script src="~/Plant02/vendor/waypoints/noframework.waypoints.js"></script>
    <script src="~/Plant02/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/Plant02/vendor/imagesloaded/imagesloaded.pkgd.min.js"></script>
    <script src="~/Plant02/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/Plant02/vendor/swiper/swiper-bundle.min.js"></script>

    <!-- Main JS File -->
    <script src="~/Plant02/js/main.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>


<style>

    header.header .container-fluid {
        background-color: aqua !important;
    }

</style>

PAWMartes/PAWMartes/PAWMartes/Views/Shared/_PiePagina.cshtml
<footer id="footer" class="footer">
    <div class="container copyright text-center mt-4">
        <p>© <span>Copyright</span> <strong class="px-1 sitename">eNno</strong> <span>All Rights Reserved</span></p>
        <div class="credits">
            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a> Distributed by <a href=“https://themewagon.com>ThemeWagon
        </div>
    </div>
    <div class="container">
        &copy; 2025 - PAWMartes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>

PAWMartes/PAWMartes/PAWMartes/Views/Shared/_Reserva.cshtml
@* @model Reserva

@{
	string Estado = string.Empty;
	if(Model.Estado)
		Estado = "Activa";
	else 
		Estado = "Cancelada";
}


<div class="card border-2" style="border-color: cornflowerblue !important;">
	<div class="card-header">
		<h3>@Model.Fecha.ToShortDateString()</h3>
	</div>
	<div class="card-body">
		<p>Usuario de Reserva: @Model.Usuario.Nombre </p>
		<p>Evento: @Model.Evento.Nombre</p>
		<p>Esta reserva se encuentra: @Estado</p>
		<div>
			<a class="btn btn-secondary" asp-action="Edit" asp-route-id="@Model.Id">Editar</a>
			<a class="btn btn-info" asp-action="Details" asp-route-id="@Model.Id">Ver Detalles</a>
			<a class="btn btn-dangerous" asp-action="Delete" asp-route-id="@Model.Id">Eliminar</a>
		</div>
	</div>
</div> *@